backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Media storage configuration
media_folder: "public/images" # Media files will be stored in the repo under public/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

# Site URL (required for local_backend)
site_url: manis-photography.vercel.app # Replace with your actual Vercel domain
display_url: manis-photography.vercel.app # Replace with your actual Vercel domain

# Local backend (optional) - enables local development
local_backend: true

collections:
  - name: "portfolio" # Used in routes, e.g., /admin/collections/portfolio
    label: "Portfolio" # Used in the UI
    folder: "content/portfolio" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["weddings", "events", "festivals", "family"]}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}

  - name: "galleries" # Used in routes, e.g., /admin/collections/galleries
    label: "Galleries" # Used in the UI
    folder: "content/galleries" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Gallery Name", name: "name", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["weddings", "events", "festivals", "family"]}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Images", name: "images", widget: "list", fields: [
          {label: "Image", name: "image", widget: "image"},
          {label: "Alt Text", name: "alt", widget: "string"},
          {label: "Title", name: "title", widget: "string"},
          {label: "Order", name: "order", widget: "number", default: 0}
        ]}
