# Local development configuration for Decap CMS
backend:
  name: test-repo
  branch: main

# Media storage configuration
media_folder: "public/images"
public_folder: "/images"

# Local backend for development
local_backend: true

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["weddings", "events", "festivals", "family"]}
      - {label: "Featured", name: "featured", widget: "boolean", default: false}
      - {label: "Order", name: "order", widget: "number", default: 0}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}

  - name: "galleries"
    label: "Galleries"
    folder: "content/galleries"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Gallery Name", name: "name", widget: "string"}
      - {label: "Category", name: "category", widget: "select", options: ["weddings", "events", "festivals", "family"]}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Images", name: "images", widget: "list", fields: [
          {label: "Image", name: "image", widget: "image"},
          {label: "Alt Text", name: "alt", widget: "string"},
          {label: "Title", name: "title", widget: "string"},
          {label: "Order", name: "order", widget: "number", default: 0}
        ]}
